### ISSUE TITLE
Why use source-maps ?

### ISSUE THREAD

**Issue by lbarman** [hmil/topside#15]
Hi,

Why do you use source-maps (and hence compressed/obfuscated main source) when going from 
`template.top.html`
to
`{template.top.ts, template.top.ts.map}` ?

The result is that `template.top.ts` is a bit cryptic to understand. Similarly, when one makes mistakes in assigning the parameters, the compiler yields:
`main.ts (5,5): Argument of type '{ name: string; name3: string; }' is not assignable to parameter of type '__Params'.`
Without source-maps, `__Params` could be `NameOfFile_TopTemplate_Params`, or something that is more informative.

Generally speaking, the generated `template.top.ts` seems complex for what it does. Any chance to reduce it to:
```
/* tslint:disable */
// This file was generated from a topside template.
// Do not edit this file, edit the original template instead.

import * as escape from 'escape-html';

export type TemplateTopTs_Params = { //LB => this would be the name of the file in CamelCase
            name: string,
            name2: string
} 

export default function(p: TemplateTopTs_Params): string {
    const name = p.name;
    const name2 = p.name2;
    return "\n\nHello " + escape("" + name) + "!\n\n";
};
```
One advantage would be to give more tools to the ts compiler to give meaningful errors, and the other would be to lower the entry barrier to using `topside`: everything that looks complex might discourage newcomers.

**Comment by lbarman** [comment]
Better:
```
/* tslint:disable */
// This file was generated from a topside template.
// Do not edit this file, edit the original template instead.

import * as escape from 'escape-html';

export default function(name: string, name2: string): string {
    return "\n\nHello " + escape("" + name) + "!\n\n";
};
```

**Comment by hmil** [comment]
Source-mapping has nothing to do with the actual name of the symbols in the generated file.

The source-map paves the way for future work to map typescript errors back to the original `.top.html` file (see p.s.).


As for the obfuscated aspect of the generated source, I agree one should thrive to make the generated code as readable as possible. However, in practice it is unlikely one should ever have to peek into the compiled template. After all, you're seldom concerned about the generated assembly when coding in C.


> `main.ts (5,5): Argument of type '{ name: string; name3: string; }' is not assignable to parameter of type '__Params'.`

You must have redacted part of the error message. The TS compiler will dig into the conflicting types and yield at least a second line with more details. Take this [playground sample](https://www.typescriptlang.org/play/#src=type%20__Params%20%3D%20%7B%0D%0A%20%20%20%20firstname%3A%20string%3B%0D%0A%20%20%20%20lastname%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20template(params%3A%20__Params)%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Atemplate(%7B%0D%0A%20%20%20%20firstname%3A%20'john'%2C%0D%0A%20%20%20%20lstaname%3A%20'cena'%0D%0A%7D)%3B%0D%0A), the compiler yields the following error message:
```
Argument of type '{ firstname: string; lstaname: string; }' is not assignable to parameter of type '__Params'.
  Object literal may only specify known properties, but 'lstaname' does not exist in type '__Params'. Did you mean to write 'lastname'?
```
Couldn't be any clearer provided one reads the whole error message.
Another example assuming I completely forgot the name of the member and I omit it. Here is what I get:
```
Argument of type '{ firstname: string; }' is not assignable to parameter of type '__Params'.
  Property 'lastname' is missing in type '{ firstname: string; }'.
```
Last, if I'm lazy I can just ask for autocompletion (ctrl+space in the playground or in VSCode) and my IDE will suggest valid members.

The other form you suggest (inline function parameters) is not desirable because it is unsafe and unclear.

Which is more resistant to refactoring?
```typescript
return view(user.firstname, user.lastname);
// 1. Could you guess what those fields will be named in the view?
// 2. Notice how I can introduce a silent bug if the order of the parameters changes.

// Or 

return view({
  username: user.firstname,
  familyname: user.lastname
});
// Despite the UI guy using different naming convention than the backend guy 
// (does that sound familiar?), this discrepancy won't even get a chance to cause a bug.
```

This last example could mean insane productivity boosts on large (and not so large) projects.

---
p.s. example of what source-maps can help achieve:
```html
@param user: User

<h1>Hello @(usre.name)</h1>
            ^^^^
            Error: usre is not defined. Did you mean "user" ?
```
The TypeScript compiler already knows how to do all of this stuff, with source-maps one can trivially map the TS error back to the html file.

**Comment by lbarman** [comment]
Ty, closing
